src/templates/api.mustache, tests/generated/v2.0/example1.ts, tests/generated/v2.0/furkot-example.ts, tests/generated/v2.0/giphy.ts, tests/generated/v2.0/github-swagger.ts, tests/generated/v3.0/swaggerhub-template.ts, tests/generated/v3.0/tsoa-odd-types-3.0.2.ts
There were a bunch of things regenerated after rebasing on `next`. Oops.
Also simplified the template a little bit.
=> Update tests after rebase

src/schema.js, src/typeFormatters.js, tests/generated/v3.0/personal-api-example.ts, tests/generated/v3.0/petstore.ts, tests/generated/v3.0/tsoa-odd-types-3.0.2.ts, tests/schemas/v3.0/petstore.yaml
feat: handle nullable option for primitive types  
This PR fix problem described in https://github.com/acacode/swagger-typescript-api/issues/36
=> [Bugfix] Nullable option for primitive types and object properties

CHANGELOG.md, package-lock.json, package.json, src/schema.js, src/typeFormatters.js, tests/generated/v3.0/personal-api-example.ts, tests/generated/v3.0/petstore.ts, tests/generated/v3.0/tsoa-odd-types-3.0.2.ts, tests/schemas/v3.0/petstore.yaml
Fixes:  
- Nullable not included in type definition ([issue](https://github.com/acacode/swagger-typescript-api/issues/36))  
Internal:
- Update `swagger2openapi`(`6.0.0`) dependency
=> Release 1.6.2

.vscode/launch.json, CHANGELOG.md, package-lock.json, package.json, src/schema.js, src/typeFormatters.js, tests/generated/v3.0/personal-api-example.ts, tests/generated/v3.0/wrong-enum-subtypes.ts, tests/schemas/v3.0/personal-api-example.json, tests/schemas/v3.0/wrong-enum-subtypes.yaml
Fixes:  
- Generating invalid code in composed schema contexts ([#51 issue](https://github.com/acacode/swagger-typescript-api/issues/51)) 
```yaml
components:
schemas:
Test:
type: object
allOf:
- type: object
properties:
x:
type: array
items:
type: string
enum:
- A-B
- type: object
properties:
y:
type: string
```
```ts
export type Test = XAB & { y?: string };
```
=> Release 1.8.3

CHANGELOG.md, package-lock.json, package.json, src/schema.js, tests/generated/v2.0/petstore-minimal.ts, tests/schemas/v2.0/petstore-minimal.json
Fixes:  
- Multiple types for a property in Swagger 2 are not handled correctly ([#55 issue](https://github.com/acacode/swagger-typescript-api/issues/55))
=> Release 1.8.4

.gitignore, CHANGELOG.md, package-lock.json, package.json, src/modelNames.js, src/routes.js, src/typeFormatters.js, tests/generated/v2.0/github-swagger.ts, tests/generated/v2.0/petstore-expanded.ts, tests/generated/v3.0/link-example.ts, tests/generated/v3.0/personal-api-example.ts, tests/generated/v3.0/tsoa-odd-types-3.0.2.ts, tests/generated/v3.0/uspto.ts, tests/schemas/v2.0/petstore-expanded.json, tests/schemas/v3.0/tsoa-odd-types-3.0.2.json, tests/spec/noClient/schema.ts, tests/spec/routeTypes/schema.ts
Features:  
- Improve the naming of model types ([#65 issue](https://github.com/acacode/swagger-typescript-api/issues/65))
=> Release 1.11.0

index.js
=> fix(cli): fix invalid default templates path

CHANGELOG.md, package-lock.json, package.json
Fixes:  
- axios vulnerability (#101 issue, thanks @Mvbraathen)
=> Release 3.1.2

CHANGELOG.md, package-lock.json, package.json, src/constants.js
Fixes:  
- `Cannot find module 'prettier-plugin-organize-imports'` #109
=> Release 4.0.1

index.d.ts, index.js, src/config.js, src/index.js, src/swagger.js
Introducted boolean options to disable SSL strict
=> disable strict ssl

CHANGELOG.md, package-lock.json, package.json, src/render/utils/index.js, templates/default/api.eta, templates/default/data-contracts.eta, templates/default/procedure-call.eta, templates/default/route-docs.eta, templates/default/route-name.eta, templates/default/route-type.eta, templates/modular/api.eta, templates/modular/data-contracts.eta, templates/modular/procedure-call.eta, templates/modular/route-docs.eta, templates/modular/route-type.eta
Features:  
- add `require()` to template `utils` object  
Docs:  
- add information about contributors
=> Release 4.0.4

CHANGELOG.md, index.d.ts, package-lock.json, package.json, src/config.js, src/formatFileContent.js, src/index.js, src/output.js, src/templates.js, src/translators/JavaScript.js
BREAKING_CHANGE:  
- remove `'prettier-plugin-organize-imports'` dependency from package  
Fixes:  
- issue #134 (Thanks @mrfratello)
=> Release 4.0.5

CHANGELOG.md, package-lock.json, package.json, templates/base/http-clients/axios-http-client.eta, templates/default/api.eta, templates/modular/api.eta, tests/spec/axios/schema.ts, tests/spec/axiosSingleHttpClient/schema.ts, tests/spec/jsAxios/schema.d.ts, tests/spec/jsAxios/schema.js
Fixes (critical):  
- Problems with using both `--axios` and `--modular` options together (TS, `organizeImports` crashed the codegeneration)
=> Release 6.1.2 (bugfix)

CHANGELOG.md, README.md, index.d.ts, index.js, package-lock.json, package.json, src/config.js, src/index.js, src/routes.js, tests/spec/moduleNameFirstTag/schema.json, tests/spec/moduleNameFirstTag/schema.ts, tests/spec/moduleNameFirstTag/test.js
Features:  
- `--module-name-first-tag` option. Splits routes based on the first tag (thanks @jnpoyser)
=> Release 6.2.0

templates/base/http-clients/fetch-http-client.eta
this should fix the bug mentioned in #236 that was introduced in #229
=> fix: add array params with key

templates/base/http-clients/axios-http-client.eta
[is it possible axios file upload #243](https://github.com/acacode/swagger-typescript-api/issues/243)
=> axios file upload formData Type

CHANGELOG.md, README.md, package-lock.json, package.json, scriptsRunner.js, templates/base/http-clients/axios-http-client.eta, tests/helpers/validateGeneratedModule.js, tests/spec/axios/schema.ts, tests/spec/axiosSingleHttpClient/schema.ts, tsconfig.json
Fixes:  
- Can't compile 9.0.0 version with --axios option (thanks @Nihisil )
=> Release 9.0.1 (bugfix)

CHANGELOG.md, index.d.ts, package-lock.json, package.json
Fixes:  
- 9.0.1 won't build with tsc when imported (thanks @mastermatt)
=> Release 9.0.2

CHANGELOG.md, package-lock.json, package.json, templates/default/api.eta, templates/modular/api.eta, tests/spec/axiosSingleHttpClient/schema.ts, tests/spec/singleHttpClient/schema.ts
Fixes:  
- Bug with --single-http-client and private `http` property
=> Release 9.1.2

README.md, package-lock.json, package.json, src/index.js, src/prettierOptions.js
Search for prettier config based on [prettier docs](https://prettier.io/docs/en/configuration.html)
#261
=> Load prettier config from user's project

index.d.ts
Has the types reflect that only one of the "inputs" is required.
=> allow mutually exclusive input options

src/schema.js, templates/base/data-contracts.eta
Add deprecated jsdocs in more areas
=> feat: add deprecated in more places

CHANGELOG.md, README.md, index.js, package-lock.json, package.json, tests/spec/cli/schema.json, tests/spec/cli/schema.ts
- fix problem linked with [this.name is not a function](https://github.com/acacode/swagger-typescript-api/issues/381)  
- [internal] add cli tests  
- fix problem with not correct working the `--no-client` option
=> Release 10.0.1

templates/base/http-clients/axios-http-client.ejs
=> fix createFormData code duplication

CHANGELOG.md, index.js, package-lock.json, package.json, tests/spec/cli/schema.ts
fix: `--api-class-name` option has no default value (#433)
=> Release 11.1.1

index.js
Fixes
Cli command never ends after typescript generation finished.
=> fixes hanging cli after execution finished

CHANGELOG.md, index.d.ts, package-lock.json, package.json, src/util/request.js
fix: problem based with http requests and `disableStrictSSL` option (#453)  
docs: update docs for `requestOptions` nodejs option
=> Release 12.0.1

CHANGELOG.md, index.d.ts, index.js, package-lock.json, package.json
fix: missing option `--extract-enums` (#344)
=> Release 12.0.2

src/swagger-schema-resolver.js, tests/spec/custom-extensions/expected.ts, tests/spec/custom-extensions/schema.json, tests/spec/custom-extensions/schema.ts, tests/spec/custom-extensions/test.js
=> fix non-object custom spec extensions

CHANGELOG.md, package-lock.json, package.json, src/schema-parser/base-schema-parsers/discriminator.js, src/schema-parser/schema-parser-fabric.js, src/type-name-formatter.js
fix: problem with incorrect settings type suffix for internal discriminator mappings
=> Release 13.0.2

index.js
=> fix: fix options manipulation

.changeset/afraid-trains-care.md, index.ts, src/commands/generate-templates/configuration.ts, src/commands/generate-templates/index.ts, src/index.ts, src/templates-worker.ts, types/index.ts
Issue introduced by https://github.com/acacode/swagger-typescript-api/pull/903
Fixes #1006
Related #954
=> Respect debug and silent logging configuration for both cli and lib modes

.changeset/moody-comics-chew.md, package.json, yarn.lock
Closes https://github.com/acacode/swagger-typescript-api/issues/1285
=> Pin versions of internal Biome packages
