- src/routes.js
- src/templates/api.mustache
- tests/generated/v2.0/another-example.ts
- tests/generated/v2.0/api-with-examples.ts
- tests/generated/v2.0/petstore-expanded.ts
- tests/generated/v2.0/petstore-minimal.ts
- tests/generated/v2.0/petstore-simple.ts
- tests/generated/v2.0/petstore-with-external-docs.ts
- tests/generated/v2.0/petstore.ts
- tests/generated/v2.0/uber.ts
- tests/generated/v3.0/allof-example.ts
- tests/generated/v3.0/anyof-example.ts
- tests/generated/v3.0/api-with-examples.ts
- tests/generated/v3.0/callback-example.ts
- tests/generated/v3.0/link-example.ts
- tests/generated/v3.0/oneof-example.ts
- tests/generated/v3.0/personal-api-example.ts
- tests/generated/v3.0/petstore-expanded.ts
- tests/generated/v3.0/petstore.ts
- tests/generated/v3.0/tsoa-odd-types-3.0.2.ts
- tests/generated/v3.0/uspto.ts
👋 Hi @acacode, I have been searching the internets for a tool to convert an OpenAPI spec into TS declarations and I was surprised with the lack of quality in this area. None of the tools seemed to offer what I was after, which is simply Type Definitions (not even the generated client) for a REST API.
I then stumbled across your repo and found it super approachable to hack on and I got the result I was after in no time.
This PR adds exports for interfaces describing the `RequestQuery`, `RequestBody` and `ResponseBody` types for each route. These are very useful things to have as type annotations for function declarations dealing with API requests/responses.
Is this something you would like to see in the project?
> Generate types for API methods

- src/templates/client.mustache
[issue 22](https://github.com/acacode/swagger-typescript-api/issues/22)
> [Bugfix] TypeScript 3.7.5 error in the strict mode inside addQueryParams method

- .travis.yml
- CHANGELOG.md
- package-lock.json
- package.json
- src/config.js
- src/index.js
- src/schema.js
- src/swagger.js
- tests/generated/v3.0/nullable-refs.ts
- tests/schemas/v3.0/nullable-refs.yaml
Fixes:  
- Handling of nullable for $ref in OpenAPI 3.0 ([issue](https://github.com/acacode/swagger-typescript-api/issues/39))  
Plus based on this issue was fixed most other problems with using `required` and `nullable` properties
> Release 1.6.3

- CHANGELOG.md
- package-lock.json
- package.json
- src/schema.js
- tests/generated/v2.0/another-example.ts
- tests/generated/v2.0/github-swagger.ts
- tests/generated/v2.0/petstore-swagger-io.ts
- tests/spec/noClient/schema.ts
- tests/spec/routeTypes/schema.ts
Fixes:  
- Broken types for arrays of union types ([issue](https://github.com/acacode/swagger-typescript-api/issues/49))
> Release 1.8.2

- README.md
- index.d.ts
- index.js
- package.json
- src/config.js
- src/files.js
- src/index.js
- src/templates.js
- tests/spec/templates/schema.json
- tests/spec/templates/schema.ts
- tests/spec/templates/spec_templates/api.mustache
- tests/spec/templates/spec_templates/client.mustache
- tests/spec/templates/spec_templates/route-types.mustache
- tests/spec/templates/test.js
This feature (closes #54) enables users to generate models and a client by providing path to a directory containing custom templates using a new CLI parameter `-t --template`.
It's also allows us to skip unnecessary templates if generating of a client or route types is not needed.
> Custom template

- CHANGELOG.md
- README.md
- index.js
- package.json
- src/config.js
- src/index.js
- src/modelTypes.js
- src/typeFormatters.js
- tests/spec/unionEnums/schema.json
- tests/spec/unionEnums/schema.ts
- tests/spec/unionEnums/test.js
Add new CLI option - `--union-enums`.  
This option allows to generate all enums as union types.  
https://github.com/acacode/swagger-typescript-api/issues/58   
For example, schema part:  
```
"StringEnum": {
"enum": ["String1", "String2", "String3", "String4"],
"type": "string"
}
```  
will be converted into:
```
export type StringEnum = "String1" | "String2" | "String3" | "String4";
```
> [Feature] `--union-enums` CLI option

- CHANGELOG.md
- README.md
- index.d.ts
- index.js
- package-lock.json
- package.json
- src/config.js
- src/files.js
- src/index.js
- src/modelTypes.js
- src/templates.js
- src/typeFormatters.js
- tests/spec/templates/schema.json
- tests/spec/templates/schema.ts
- tests/spec/templates/spec_templates/api.mustache
- tests/spec/templates/spec_templates/client.mustache
- tests/spec/templates/spec_templates/route-types.mustache
- tests/spec/templates/test.js
- tests/spec/unionEnums/schema.json
- tests/spec/unionEnums/schema.ts
- tests/spec/unionEnums/test.js
- `--templates` CLI option. [[feature request]](https://github.com/acacode/swagger-typescript-api/issues/54)  
Provide custom `mustache` templates folder which allows to generate custom code (models, Api class, routes)  
- `--union-enums` CLI option. [[feature request]](https://github.com/acacode/swagger-typescript-api/issues/58)  
Allows to generate all enums as union types.  
For example, schema part:  
```
"StringEnum": {
"enum": ["String1", "String2", "String3", "String4"],
"type": "string"
}
```  
will be converted into:
```
export type StringEnum = "String1" | "String2" | "String3" | "String4";
```  
Closes https://github.com/acacode/swagger-typescript-api/issues/54  
Closes https://github.com/acacode/swagger-typescript-api/issues/58
> Release 1.10.0

- README.md
- index.d.ts
- package-lock.json
- package.json
- src/index.js
- src/swagger.js
- tests/spec/specProperty/schema.json
- tests/spec/specProperty/schema.ts
- tests/spec/specProperty/test.js
Add a `spec` option to help converting schema object. Really require this as I am building a tool, which do not expect to read schema from a public url nor local path.
> Complete #69 add spec option to convert schema object

- src/templates/defaults/http-client.mustache
It's unfortunately not safe to clone a stream unless each of the clones are processed in parallel. However, currently, the original response is not even being exposed to consumers until the cloned stream is fully processed. Thus, we can end up with a hang when handling large JSON responses, particularly on NodeJS when using node-fetch. See:
https://github.com/node-fetch/node-fetch/issues/139
https://github.com/node-fetch/node-fetch/issues/665
This change does have the side-effect that **consumers will be unable to rewind the stream and inspect the body in the event that JSON parsing fails**. If it succeeds, then we're provided with the parsed body, so it's a non-issue in that case.
**This PR is breaking** for the reason outlined above. However, the breaking change does not affect regular …
> Fixed unsafe clone() of Response causing json() hang.

- CHANGELOG.md
- README.md
- index.d.ts
- index.js
- package-lock.json
- package.json
- tests/spec/moduleNameIndex/schema.json
- tests/spec/moduleNameIndex/schema.ts
- tests/spec/moduleNameIndex/test.js
Features:  
- `--moduleNameIndex` option. determines which path index should be used for routes separation  
Examples:  
GET:api/v1/fruites/getFruit -> index:2 -> moduleName -> fruites
GET:api/v1/fruites/getFruit -> index:0 -> moduleName -> api
> Release 3.1.0

- CHANGELOG.md
- package-lock.json
- package.json
- src/modelNames.js
- src/schema.js
- tests/generated/v2.0/another-example.ts
- tests/schemas/v2.0/another-example.json
Fixes:  
- `name.includes is not a function` (issue #98)
> Release 3.1.1

- CHANGELOG.md
- package-lock.json
- package.json
- src/routes.js
- templates/default/procedure-call.eta
- templates/default/route-docs.eta
- templates/default/route-type.eta
- templates/modular/procedure-call.eta
- templates/modular/route-docs.eta
- templates/modular/route-type.eta
- tests/spec/templates/spec_templates/procedure-call.eta
- tests/spec/templates/spec_templates/route-docs.eta
- tests/spec/templates/spec_templates/route-type.eta
Fixes:  
- `Unexpected token '.'` on v4 (Thanks @savingprivatebryan for issue #111)  
Replaced all new syntax sugar like `?.` or `??` to prev. alternatives for support nodejs 12
> Release 4.0.2

- CHANGELOG.md
- README.md
- index.d.ts
- index.js
- package-lock.json
- package.json
- src/config.js
- src/index.js
- src/swagger.js
Features:  
- `--disableStrictSSL` option for disable strict SSL statement with fetching swagger schema. (Thanks @kel666 for PR with feature request)  
This option fix problem #114
> Release 4.0.3

- .prettierignore
- CHANGELOG.md
- README.md
- index.js
- package-lock.json
- package.json
- src/files.js
- src/formatFileContent.js
- src/index.js
- src/render/utils/index.js
Features:  
- Improve `require()` function used in ETA templates (using relative path imports)  
- `--clean-output` option.  
clean output folder before generate api  
Fixes:  
- Error: `Unexpected token =` (Issue #136, Thanks @jlow-mudbath)  
- Output folder creation (Issue #137, Thanks @Rinta01)  
Create output folder if it is not exist
> Release 4.1.0

- templates/modular/http-client.eta
If `requestParams` contained headers, the whole headers would be replaced by these ones, wiping out the automatic `Content-Type` header.
Putting the `requestParams` spread first fixes it, as the re-definition of `headers` will overwrite them.
> Fix header overwrite in modular API template.

- templates/default/http-client.eta
- templates/modular/http-client.eta
Fixes: https://github.com/acacode/swagger-typescript-api/issues/172
It's better to let the browser handle setting of this content-type, since it will add the correct boundary.
> Don't set multipart/form-data content-type

- templates/default/http-client.eta
- templates/modular/http-client.eta
It might sound strange to stringify string data, but the alternative is to expect a user to wrap it in quotes him/herself 
```
`"${dataToPass}"`
```
> Also Json stringify string data

- src/templates.js
This allows overriding specific template files and fallback on the defaults.
Before this change, the behavior was for the tool to fail with `Error: ENOENT: no such file or directory` if one of the template files in a custom templates directory does not exist.
Caveat: With this fix it will still error if the overridden template uses `includeFile` on a template file that is not overridden:
```
Error [Eta Error]: Could not find the template "./route-docs". Paths tried: /redacted/route-docs.eta
```
Example output:
```
✨ try to read templates from directory "/redacted"
❗❗❗ data contracts template not found in ./data-contracts.eta
Code generator will use the default template
❗❗❗ http client template not found in ./http-client.eta
Code generator will use the default template
❗❗❗ route types …
```
> Do not fail if template file does not exist

- CHANGELOG.md
- package-lock.json
- package.json
- src/templates.js
Fixes:  
- Do not fail if template file does not exist (issue #166, thanks @armsnyder )  
Caveat: With this fix it will still error if the overridden template uses `includeFile` on a template file that is not overridden
> Release 5.1.7

- README.md
- index.d.ts
- index.js
- package.json
- src/config.js
- src/index.js
- src/routes.js
- tests/spec/moduleNameFirstTag/schema.json
- tests/spec/moduleNameFirstTag/schema.ts
- tests/spec/moduleNameFirstTag/test.js
Adds an option to split the routes/API based on the first tag of the operation.
This feature is inspired by the `--module-name-index` option, which didn't quite work for our use case. We have more complex nested routes - like `/api/company/{companyId}/employee/{employeeId}`, which are driven by corporate security policies. Splitting on the index in the URL didn't work - in this example we have company operations and employee operations.
The solution: use the first tag for the operation as the module name. Tags in the openapi/swagger spec are collections/arrays, so should be stable.
For us, we then create a company class, an employee class, etc.
> Split routes based on first tag

- CHANGELOG.md
- index.d.ts
- package-lock.json
- package.json
- templates/base/http-clients/axios-http-client.eta
- tests/spec/axios/schema.ts
- tests/spec/axiosSingleHttpClient/schema.ts
- tests/spec/jsAxios/schema.js
Fixes:  
- missing `generateUnionEnums?: boolean;` in `index.d.ts` file (thanks @artsaban)  
- missing default params to axios http client (`--axios`) (issue #192, thanks @Nihisil)
> Release 6.2.1

- CHANGELOG.md
- README.md
- index.d.ts
- index.js
- package-lock.json
- package.json
- src/config.js
- src/index.js
- src/modelNames.js
- src/modelTypes.js
- src/routes.js
- src/schema.js
- tests/spec/typeSuffixPrefix/schema.json
- tests/spec/typeSuffixPrefix/schema.ts
- tests/spec/typeSuffixPrefix/test.js
Features:  
- `--type-suffix` option. Allows to set suffix for data contract name. (issue #191, thanks @the-ult)  
- `--type-prefix` option. Allows to set prefix for data contract name. (issue #191, thanks @the-ult)  
Examples [here](https://github.com/acacode/swagger-typescript-api/blob/next/tests/spec/typeSuffixPrefix/schema.ts)  
- `onFormatTypeName(usageTypeName, rawTypeName)` hook. Allow to format data contract names as you want.  
Internal:  
- rename and split `checkAndRenameModelName` -> `formatModelName`, `fixModelName`
> Release 6.3.0

- src/schema.js
- tests/spec/unionEnums/schema.json
- tests/spec/unionEnums/schema.ts
Hello.
First, I really appreciate typescript-specialized codegen project!
I've got here searching for alternatives to swagger-codegen, openapi-generator as both of these didn't feel seamless & neat with typescript.
Trying swagger-typescript-api, I found this little bug. please give me a feedback :)
as-is:
```typescript
export type BooleanEnum = "true" | "false";
```
to-be:
```ts
export type BooleanEnum = true | false;
```
> Fix boolean enum handling

- templates/base/http-clients/fetch-http-client.eta
This PR introduces a small feature where fetch function used within the HttpClient class can be customized.
Allowing to pass a custom fetch function enables a few things -
- Add implicit telemetry to the fetch function
- hook into before and after the function call is made in a generic way
- Handle special cases in a generic way around fetch function itself
Implements the feature from: #219
> Allow passing custom fetch function

- templates/base/http-clients/fetch-http-client.eta
This is a fix for #222 
I also renamed the function to make that part of the code it bit clearer.
> Fix: query param array serialization

- src/routes.js
OpenAPI allows specifying range response codes (https://swagger.io/docs/specification/describing-responses/). I don't think it's particularly good code style tbh, but "2xx" should still probably be considered a successful response
> Consider 2xx a successful status

- index.d.ts
- index.js
- src/config.js
- src/index.js
- src/swagger.js
Hi, recently I had problems using swagger-typescript-api at work.
After some investigations I found that our corporate proxy was the problem, and was simply solved by adding "proxy: false" to Axios options.
I also added a catch clause in the Axios GET to print out some infos and to avoid missing "catch" error from nodeJS.
Hope you will include it in next release!
Tnx
Fabio
> disableProxy option, added catch to axios get

- index.d.ts
`silent` was added as an option in 6.1.0.
https://github.com/acacode/swagger-typescript-api/pull/185
> fix(types): add silent as param in declarations

- templates/base/http-clients/axios-http-client.eta
- tests/spec/axios/schema.ts
- tests/spec/axiosSingleHttpClient/schema.ts
- tests/spec/jsAxios/schema.js
Currently FormData is not correctly handled in the axios template.
FormData is correctly built but not passed to axios, causing the requests to fail.
> fix: formdata in axios template

- src/routes.js
This commit adds additional type information to the route's response
object that allows types to be created that express the combination
of status code, data and headers for each response.
This type information can be used to "narrow" a response type based on
an HTTP status code. This narrowing is useful since it can prevent type
mismatches where a status code is presumed to have one type but in actuality
it returns another.
Additionally, response headers are now associated with data types and status
codes rather than being free form.
A caveat right now is that only there are no response codes like 3XX or
5XX, every code must be explicitly listed.
> Feature: add full response typing for status code, data and headers.

- README.md
- index.d.ts
- index.js
- package.json
- src/config.js
- src/index.js
- src/swagger.js
- tests/spec/patch/schema.json
- tests/spec/patch/schema.ts
- tests/spec/patch/test.js
This PR adds the possibility to pass patch as an option.
This option is passed to the swagger2openapi converter to automatically **fix small errors in swagger definition code** like : 
- collectionFormat is only applicable to header.type array
- operation.consumes must be an array
- info.termsOfService must be a URL 
...
You can find all errors by searching (patchable) in [this file](https://github.com/Mermade/oas-kit/blob/706d2b8b548a0e13aabd5ff4811a6ba3784831a8/packages/swagger2openapi/index.js)
Without this option, the converter will throw an error and stop the generation.
Example : 
```
swagger-typescript-api\src\swagger.js:80
throw new Error(err);
^
Error: S2OError: (Patchable) info.termsOfService must be a URL
at swagger-typescript-api\src\swagger.js:80:19
at …
```
> Feature: allow passing "patch" option to "swagger2openapi"

- index.js
- src/swagger.js
If we have an error in axios, for example invalid URL, we never catch this error in a Promise wrapper
> fix(reject): fix reject and exit with code 1 if error

- templates/base/http-clients/fetch-http-client.eta
Passed [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) is overridden by `signal: undefined` here: https://github.com/acacode/swagger-typescript-api/blob/7df956c236d1e7fc051658cd7012c8ea22286b44/templates/base/http-clients/fetch-http-client.eta#L186 it will never be passed to `fetch` function
> Fix: unable to cancel fetch request with AbortSignal

- src/schema.js
COMPLEX_NOT_OF does not exist on SCHEMA_TYPES.
This caused a failure when generating TypeScript types from a schema for myself. Changing to COMPLEX_NOT fixed it.
> fix: change COMPLEX_NOT_OF to COMPLEX_NOT

- templates/base/route-docs.ejs
- templates/default/procedure-call.ejs
- templates/modular/procedure-call.ejs
- tests/spec/responses/expected.ts
- tests/spec/responses/schema.ts
- tests/spec/typeSuffixPrefix/expected.ts
- tests/spec/typeSuffixPrefix/schema.ts
If you are using VSCode and are trying to contribute to this project, there is a chance that you have the setting `"files.trimTrailingWhitespace": true,` enabled, like me.
And it took me some time to understand why my test suite was failiing.
I think this small fix can be useful even if you don't enforce any particular convention regarding trailing spaces.
What do you think?
> chore: remove useless trailing whitespaces which make test edit harder

- package.json
- templates/base/data-contract-jsdoc.ejs
- tests/spec/deprecated/expected.ts
- tests/spec/deprecated/schema.json
- tests/spec/deprecated/schema.ts
- tests/spec/deprecated/test.js
We sometimes have in our OpenAPI schema some properties with the `"deprecated": false` flag.
These properties are annotated as `@deprecated` even with the flag set to `false`.
This PR fixes this issue and add a related test.
> fix(deprecated): property with deprecated=false was shown as @deprecated

- README.md
- index.d.ts
Looks like this is possible (not supported, maybe?) but not documented. Helps out a lot with using the exposed API with custom behavior on the tool's output.
> document approach to disabling output

- CHANGELOG.md
- index.d.ts
- package-lock.json
- package.json
- src/configuration.js
- src/swagger-schema-resolver.js
- src/util/request.js
BREAKING_CHANGE: replace `axios` to `node-fetch`  
feat: ability to send request options for getting swagger schema by url (`requestOptions` property)
> Release 11.1.0

- src/schema-parser/schema-routes.js
- tests/generated/v2.0/api-with-examples.ts
- tests/schemas/v2.0/api-with-examples.yaml
Fixes acacode/swagger-typescript-api#440
> fix: handling for content-type application/json with a charset parameter

- package-lock.json
- package.json
Updated `eta` package to 2.0.0, since [CVE-2022-25967](https://github.com/advisories/GHSA-mf6x-hrgr-658f)
> Update vulnerable deps

- README.md
- src/schema-parser/schema-parser.js
- src/schema-parser/schema-routes.js
- src/schema-parser/schema-utils.js
- src/util/name-resolver.js
https://github.com/acacode/swagger-typescript-api/issues/506
I've fixed two problems:
- extracted enum from query params name resolving (permanent `NameName` in extracted enum)
- incorrect extracted enum name within request type (flaky `NameName` within type request definition)
<details>
<summary>Swagger to reproduce</summary>
```json
{
"openapi": "3.0.2",
"info": {
"title": "Some Public API",
"version": "0.0.1"
},
"paths": {
"/a/b/c": {
"get": {
"tags": [
"tag1"
],
"summary": "get A",
"operationId": "get_a_b_c_get",
"parameters": [
{
"required": false,
"schema": {
"type": "array",
"items": {
"$ref": "#/components/schemas/VmState"
}
},
"name": "statuses",
"in": "query"
},
{
"required": false,
"schema": {
"title": "Order By",
"enum": [
"created_time"
],
"type": "string",
"default": …
```
> fix: extracting enums along with extracting request params [#506]

- src/schema-routes/schema-routes.js
I appears that the behaviour described in docs to skip the endpoint when `onCreateRoute` hook returns false was removed in v11
[change](https://github.com/acacode/swagger-typescript-api/commit/2d7925e96f87f269402122b00641652078f77d47#diff-481bff25593155cc0695aeb0f112c109e3075ef703d254734ec2a3c5266ee0beL676) -> `src/routes.js`
> fix: onCreateRoute skip behaviour

- templates/base/http-clients/axios-http-client.ejs
- templates/default/api.ejs
- templates/modular/api.ejs
- tests/spec/axios/expected.ts
- tests/spec/axios/schema.ts
- tests/spec/axiosSingleHttpClient/expected.ts
- tests/spec/axiosSingleHttpClient/schema.ts
- tests/spec/jsAxios/schema.d.ts
The original code was importing both functions and types together from the axios library. 
To make the code more readable **and follow best practices**, I've separated the import statements into two lines. 
The first line now imports only the type definitions, i.e., AxiosInstance, AxiosRequestConfig, HeadersDefaults, and ResponseType from axios.
The second line imports the axios library itself.
Note:
_I've observed that in Vue projects built with Vite, the current approach **does not only** cause issues with the linter but **also leads to build failures**. The build process does not produce runnable code if type imports are not separated from library imports. Although the root cause of this behavior in Vite is unclear for me, these changes address this problem and ensure successful …
> Use type-only import for axios types

- src/schema-routes/schema-routes.js
Fix regex failure to match path parameters such as /api/store/{2dId}
> Fix regex to match numbers in path parameters

- CHANGELOG.md
- package-lock.json
- package.json
- src/schema-parser/base-schema-parsers/discriminator.js
- tests/spec/discriminator/expected.ts
- tests/spec/discriminator/schema.json
- tests/spec/discriminator/schema.ts
fix: problem with type `any` as base type of discriminator schema (cases when schema without discriminator is empty)
> Release 13.0.3

- src/configuration.js
Revert breaking change introduced in cosmiconfig v9.0.0
Fixes https://github.com/acacode/swagger-typescript-api/issues/780
> fix: support shared prettier config files

- .gitignore
- index.js
- package.json
- src/constants.js
- tsconfig.json
- tsup.config.ts
- yarn.lock
> Add support for both ESM and CJS

- templates/base/http-clients/fetch-http-client.ejs
- tests/__snapshots__/extended.test.ts.snap
- tests/__snapshots__/simple.test.ts.snap
- tests/spec/another-query-params/__snapshots__/basic.test.ts.snap
- tests/spec/custom-extensions/__snapshots__/basic.test.ts.snap
- tests/spec/defaultAsSuccess/__snapshots__/basic.test.ts.snap
- tests/spec/defaultResponse/__snapshots__/basic.test.ts.snap
- tests/spec/deprecated/__snapshots__/basic.test.ts.snap
- tests/spec/dot-path-params/__snapshots__/basic.test.ts.snap
- tests/spec/enumNamesAsValues/__snapshots__/basic.test.ts.snap
- tests/spec/extractRequestBody/__snapshots__/basic.test.ts.snap
- tests/spec/extractRequestParams/__snapshots__/basic.test.ts.snap
- tests/spec/extractResponseBody/__snapshots__/basic.test.ts.snap
- tests/spec/extractResponseError/__snapshots__/basic.test.ts.snap
- tests/spec/jsAxios/__snapshots__/basic.test.ts.snap
- tests/spec/moduleNameFirstTag/__snapshots__/basic.test.ts.snap
- tests/spec/moduleNameIndex/__snapshots__/basic.test.ts.snap
- tests/spec/on-insert-path-param/__snapshots__/basic.test.ts.snap
- tests/spec/patch/__snapshots__/basic.test.ts.snap
- tests/spec/responses/__snapshots__/basic.test.ts.snap
- tests/spec/singleHttpClient/__snapshots__/basic.test.ts.snap
- tests/spec/sortTypes-false/__snapshots__/basic.test.ts.snap
- tests/spec/sortTypes/__snapshots__/basic.test.ts.snap
- tests/spec/typeSuffixPrefix/__snapshots__/basic.test.ts.snap
- tests/spec/unionEnums/__snapshots__/basic.test.ts.snap
This PR fixes an issue where `contentFormatter` was returning an empty `FormData` object, effectively not allowing to submit any form data when the content type is set to 'formdata'
> Fix contentFormatter for FormData returning an empty FormData object

- templates/base/http-clients/axios-http-client.ejs
- tests/spec/axios/__snapshots__/basic.test.ts.snap
- tests/spec/axiosSingleHttpClient/__snapshots__/basic.test.ts.snap
- tests/spec/js/__snapshots__/basic.test.ts.snap
When in createFormData in axios-http-client, first check if the input is of type FormData and if so, return it.
> Checking if instanceof FormData before creating one

- src/schema-routes/schema-routes.js
`security` in the original OpenAPI document is not included in `routeInfo.raw`. This PR addes it.
> feat: add security in raw route info

- README.md
- index.d.ts
- index.js
- src/templates-worker.js
Closes https://github.com/acacode/swagger-typescript-api/issues/806
> Get rid of `require`

- index.js
It should finally fix #806
Added interop default, because currently importing of custom config with `export default` is not working properly.
Also reorganized custom config logs a bit:
- logging "found custom config" only if it really loads
- otherwise showing error, instead of silently ignoring custom config
> Custom config: handle default export

- src/schema-routes/schema-routes.js
- tests/__snapshots__/extended.test.ts.snap
- tests/spec/extractResponseBody/__snapshots__/basic.test.ts.snap
When using the `--extract-response-body` option, the format option of requests disappears.
For example (from `tests/spec/extractResponseBody.js`):
When running with extractResponseBody: true, the generated code looks like this:
```typescript
this.request<FindPetsByStatusDataTTT, void>({
path: `/pet/findByStatus`,
method: "GET",
query: query,
secure: true,
...params,
}),
```
However, when running without `extractResponseBody: true`, the generated code includes the format option:
```typescript
this.request<PetTTT[], void>({
path: `/pet/findByStatus`,
method: "GET",
query: query,
secure: true,
format: "json",   // <- this
...params,
}),
```
I attempted to copy `contentKind` to make the format is in the generated request options. I'm not sure if this is the good approach.
> fix: format option of requests when using extractResponseBody

- templates/base/http-clients/axios-http-client.ejs
- tests/spec/axios/__snapshots__/basic.test.ts.snap
- tests/spec/axiosSingleHttpClient/__snapshots__/basic.test.ts.snap
- tests/spec/js/__snapshots__/basic.test.ts.snap
This MR reverts [Don't set multipart/form-data content-type #173](https://github.com/acacode/swagger-typescript-api/pull/173) for the [`axios-http-client.ejs`](https://github.com/acacode/swagger-typescript-api/blob/c166ca8060bb956c25a4bc936513b323f404c385/templates/base/http-clients/axios-http-client.ejs#L130) template since axios doesn't automatically add this header.
This fixes issue #671.
> Fix #671 -  Content-Type: "multipart/form-data" is ignored (when using axios)

- templates/base/http-clients/fetch-http-client.ejs
- tests/__snapshots__/extended.test.ts.snap
- tests/__snapshots__/simple.test.ts.snap
- tests/spec/another-query-params/__snapshots__/basic.test.ts.snap
- tests/spec/custom-extensions/__snapshots__/basic.test.ts.snap
- tests/spec/defaultAsSuccess/__snapshots__/basic.test.ts.snap
- tests/spec/defaultResponse/__snapshots__/basic.test.ts.snap
- tests/spec/deprecated/__snapshots__/basic.test.ts.snap
- tests/spec/dot-path-params/__snapshots__/basic.test.ts.snap
- tests/spec/enumNamesAsValues/__snapshots__/basic.test.ts.snap
- tests/spec/extractRequestBody/__snapshots__/basic.test.ts.snap
- tests/spec/extractRequestParams/__snapshots__/basic.test.ts.snap
- tests/spec/extractResponseBody/__snapshots__/basic.test.ts.snap
- tests/spec/extractResponseError/__snapshots__/basic.test.ts.snap
- tests/spec/jsAxios/__snapshots__/basic.test.ts.snap
- tests/spec/moduleNameFirstTag/__snapshots__/basic.test.ts.snap
- tests/spec/moduleNameIndex/__snapshots__/basic.test.ts.snap
- tests/spec/on-insert-path-param/__snapshots__/basic.test.ts.snap
- tests/spec/patch/__snapshots__/basic.test.ts.snap
- tests/spec/responses/__snapshots__/basic.test.ts.snap
- tests/spec/singleHttpClient/__snapshots__/basic.test.ts.snap
- tests/spec/sortTypes-false/__snapshots__/basic.test.ts.snap
- tests/spec/sortTypes/__snapshots__/basic.test.ts.snap
- tests/spec/typeSuffixPrefix/__snapshots__/basic.test.ts.snap
- tests/spec/unionEnums/__snapshots__/basic.test.ts.snap
Reverts acacode/swagger-typescript-api#747
> Revert "Fix contentFormatter for FormData returning an empty FormData object"

- cli/execute.js
- cli/index.js
- cli/process-option.js
- src/code-formatter.js
- src/code-gen-process.js
- src/commands/generate-templates/templates-gen-process.js
- src/configuration.js
- src/schema-components-map.js
- src/schema-parser/base-schema-parsers/array.js
- src/schema-parser/base-schema-parsers/complex.js
- src/schema-parser/base-schema-parsers/discriminator.js
- src/schema-parser/base-schema-parsers/enum.js
- src/schema-parser/base-schema-parsers/object.js
- src/schema-parser/base-schema-parsers/primitive.js
- src/schema-parser/complex-schema-parsers/all-of.js
- src/schema-parser/complex-schema-parsers/any-of.js
- src/schema-parser/complex-schema-parsers/one-of.js
- src/schema-parser/schema-formatters.js
- src/schema-parser/schema-parser-fabric.js
- src/schema-parser/schema-utils.js
- src/schema-routes/schema-routes.js
- src/schema-walker.js
- src/swagger-schema-resolver.js
- src/templates-worker.js
- src/type-name-formatter.js
- src/util/file-system.js
- src/util/logger.js
- src/util/name-resolver.js
- src/util/object-assign.js
- src/util/request.js
In the long term, we will only use a minimal amount of lodash to remove the implicit diff to stdlib for TypeScript rewrite.
> Reduce use of lodash

- index.ts
- src/index.ts
Issue introduced by #903
Fixes #942
> Respect silent option by only logging errors

- index.js
Ref: https://github.com/acacode/swagger-typescript-api/pull/930
> use import pattern that supports windows external drives

- .changeset/orange-dogs-lay.md
- templates/base/route-name.ejs
- tests/__snapshots__/extended.test.ts.snap
- tests/__snapshots__/simple.test.ts.snap
- tests/spec/axios/__snapshots__/basic.test.ts.snap
- tests/spec/axiosSingleHttpClient/__snapshots__/basic.test.ts.snap
- tests/spec/js/__snapshots__/basic.test.ts.snap
- tests/spec/jsAxios/__snapshots__/basic.test.ts.snap
- tests/spec/patch/__snapshots__/basic.test.ts.snap
- tests/spec/routeTypes/__snapshots__/basic.test.ts.snap
- tests/spec/sortTypes-false/__snapshots__/basic.test.ts.snap
- tests/spec/sortTypes/__snapshots__/basic.test.ts.snap
- tests/spec/typeSuffixPrefix/__snapshots__/basic.test.ts.snap
`/group/{gid}/user` and `/group/{gid}/user/{uid}` should be generated as `groupUserList` / `groupUserDetail` instead of ` groupUser` / `groupUser2`
> Fix route regex pattern in route name generation

- .changeset/honest-bears-stay.md
- src/schema-routes/schema-routes.ts
- tests/spec/defaultAsSuccess/__snapshots__/basic.test.ts.snap
- tests/spec/extractRequestParams/__snapshots__/basic.test.ts.snap
- tests/spec/extractRequestParams/schema.json
Fixes the way how query params are parsed when they consist of one letter or the first letter is followed by underscore.
Original #686 by @ahoseinian was needed to be rebased.
So I did it myself because of no activity there.
> Fix route param parsing when the param begins with just one letter (rebased original PR #686 by @ahoseinian)

- .changeset/loose-lies-fetch.md
- src/configuration.ts
- src/schema-components-map.ts
- src/schema-parser/schema-parser-fabric.ts
- src/schema-routes/schema-routes.ts
- types/index.ts
> Feature more info about extracted types

- .changeset/free-chairs-film.md
- .changeset/honest-bears-stay.md
- .changeset/loose-lies-fetch.md
- CHANGELOG.md
- package.json
Reverts acacode/swagger-typescript-api#1098
> Revert "Version Packages"

- .changeset/early-kings-marry.md
- .changeset/easy-paths-check.md
- .changeset/moody-dodos-brake.md
- index.ts
> Fix CLI argument definitions and client generation logic

- .changeset/easy-paths-check.md
- .changeset/five-moles-wonder.md
- index.ts
Fixes https://github.com/acacode/swagger-typescript-api/issues/1105
Fixes https://github.com/acacode/swagger-typescript-api/issues/1099
> Fix default value for `no-client` argument in command configuration

- .changeset/dark-memes-help.md
- index.ts
Closes https://github.com/acacode/swagger-typescript-api/issues/1117
> Fix default value for `no-client` option in `generateCommand` to `false`

- .changeset/fancy-actors-wait.md
- index.ts
- package.json
- yarn.lock
> Use `c12` for wider configuration file format support

- .changeset/mean-ghosts-post.md
- src/code-gen-process.ts
- src/schema-components-map.ts
- tests/spec/discriminator/__snapshots__/basic.test.ts.snap
- tests/spec/enumNotFirstInComponents/__snapshots__/basic.test.ts.snap
- tests/spec/enumNotFirstInComponents/basic.test.ts
- tests/spec/enumNotFirstInComponents/schema.json
- tests/spec/enums-2.0/__snapshots__/basic.test.ts.snap
- tests/spec/extractRequestBody/__snapshots__/basic.test.ts.snap
- tests/spec/extractResponseBody/__snapshots__/basic.test.ts.snap
- tests/spec/extractResponseError/__snapshots__/basic.test.ts.snap
- tests/spec/moduleNameFirstTag/__snapshots__/basic.test.ts.snap
- tests/spec/moduleNameIndex/__snapshots__/basic.test.ts.snap
- tests/spec/unionEnums/__snapshots__/basic.test.ts.snap
The schema parser is recursive. When we parse the discriminators if the enums aren't yet parsed so they aren't used.
We have to be sure enums are at the top of the components list to ensure there are parsed before other components.
This fix #699.
> fix: Ensure enums are at the top of the components to avoid issue on recursive schema parsing

- src/schema-routes/schema-routes.ts
- fix a typo in schema-routes comment
- `yarn test` *(fails: Couldn't find the node_modules state file)*
> Fix swagger2openapi typo

- src/util/file-system.ts
- export FILE_PREFIX constant and reuse it
- refactor file-system util to import FILE_PREFIX
- `corepack enable && yarn lint && yarn test` *(fails: Couldn't find the node_modules state file)*
> Use shared FILE_PREFIX

- src/util/name-resolver.ts
- fix `unreserve` so it updates the internal reserved list
- remove the previously added unit test
- `corepack enable && yarn test` *(fails: Couldn't find the node_modules state file)*
> Fix unreserve logic

- .changeset/small-birds-smile.md
- index.ts
- src/type-name-formatter.ts
- correct CLI description for `path` option
- clarify warning message for wrong model name
- document these fixes in a changeset
- `npm test` *(fails: vitest not found)*
- `npm run lint` *(fails: biome not found)*
- `npm run format:check` *(fails: biome not found)*
> Fix typos in messages

- .changeset/tame-poets-act.md
- index.ts
See https://github.com/acacode/swagger-typescript-api/commit/1cb1c9c0d39dacefb89a6b44eaf2a6266334f3c6#r159310334
> Revert "Integrate `generateCommand` arguments and run method into main command (#1198)"

- .changeset/big-sheep-see.md
- src/type-name-formatter.ts
- tests/spec/enumIncludesNumber/__snapshots__/basic.test.ts.snap
- tests/spec/enumIncludesNumber/basic.test.ts
- tests/spec/enumIncludesNumber/schema.json
Hi :wave: 
Before, enum names like ENUM_123_VALUE lost their underscores and became ENUM123VALUE.  
This change keeps the underscores so the names stay correct. (Fixes #276)
Best,
Parsa
> fix: keep underscores in enum names with numbers (like ENUM_123_VALUE)

- .changeset/loud-dancers-shake.md
- templates/base/http-clients/fetch-http-client.ejs
- tests/__snapshots__/extended.test.ts.snap
- tests/__snapshots__/simple.test.ts.snap
- tests/spec/another-query-params/__snapshots__/basic.test.ts.snap
- tests/spec/custom-extensions/__snapshots__/basic.test.ts.snap
- tests/spec/defaultAsSuccess/__snapshots__/basic.test.ts.snap
- tests/spec/defaultResponse/__snapshots__/basic.test.ts.snap
- tests/spec/deprecated/__snapshots__/basic.test.ts.snap
- tests/spec/dot-path-params/__snapshots__/basic.test.ts.snap
- tests/spec/enumNamesAsValues/__snapshots__/basic.test.ts.snap
- tests/spec/enumNotFirstInComponents/__snapshots__/basic.test.ts.snap
- tests/spec/extractRequestBody/__snapshots__/basic.test.ts.snap
- tests/spec/extractRequestParams/__snapshots__/basic.test.ts.snap
- tests/spec/extractResponseBody/__snapshots__/basic.test.ts.snap
- tests/spec/extractResponseError/__snapshots__/basic.test.ts.snap
- tests/spec/jsAxios/__snapshots__/basic.test.ts.snap
- tests/spec/jsonapi-media-type/__snapshots__/basic.test.ts.snap
- tests/spec/moduleNameFirstTag/__snapshots__/basic.test.ts.snap
- tests/spec/moduleNameIndex/__snapshots__/basic.test.ts.snap
- tests/spec/on-insert-path-param/__snapshots__/basic.test.ts.snap
- tests/spec/operationId-starting-with-number/__snapshots__/basic.test.ts.snap
- tests/spec/patch/__snapshots__/basic.test.ts.snap
- tests/spec/responses/__snapshots__/basic.test.ts.snap
- tests/spec/singleHttpClient/__snapshots__/basic.test.ts.snap
- tests/spec/sortTypes-false/__snapshots__/basic.test.ts.snap
- tests/spec/sortTypes/__snapshots__/basic.test.ts.snap
- tests/spec/typeSuffixPrefix/__snapshots__/basic.test.ts.snap
- tests/spec/unionEnums/__snapshots__/basic.test.ts.snap
Several open issues are caused by the `multipart/form-data` formatter trying to provide a simple API based on an input of type `Object`. However, `Object` can not express some of the typical use cases of a multipart request. On the other hand, `FormData` could.
One example (mentioned in #705 and #965) is sending a requested with multiple entries belonging to the same "key". Since a `FormData` object allows one key to be mapped to multiple values, one can simply do:
```ts
f = new FormData()
f.append('files', new Blob())
f.append('files', new Blob())
[...f.keys()] // This gives 2 entries, as expected
```
This is clearly not possible with an `Object`, where the key-value relationship is 1:1. #1000 tries to achieve this by automatically converting `Array` values to multiple `FormData` keys. …
> Fix handling of input of type FormData for the Fetch client

- .changeset/itchy-owls-beg.md
- src/schema-components-map.ts
Inside of an `ejs`, when using
```js
const { getComponentByRef } = utils;
getComponentByRef('XXX')
```
You'll get
```
Cannot read properties of undefined (reading '_data')
```
> fix: SchemaComponentsMap bindings

- .changeset/slow-vans-win.md
- src/code-gen-process.ts
- src/schema-components-map.ts
- tests/spec/discriminator/__snapshots__/basic.test.ts.snap
- tests/spec/enumNotFirstInComponents/__snapshots__/basic.test.ts.snap
The goal of this merge request is to ensure discriminators are at the (not so) very first place in generation, just after enums.
If they're not, that will cause cyclic errors in typescript.
> Set discriminators types before other types than enums

- .changeset/lazy-rules-guess.md
- package.json
- yarn.lock
> Move @types/lodash and openapi-types to dependencies
